In [ ]:
#!conda list

In [52]:
import pygrib
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [2]:
grbs = pygrib.open('2022-1.grib')

In [3]:
grb=grbs[1:]
grb.append(grbs[len(grb)+1])

In [ ]:
#selected_grbs=grbs.select(shortName="u",typeOfLevel='isobaricInhPa',level=[500,700,800,925,1000])
#selected_grbs[0]

In [4]:
numChannels=12
gridShape=(221,381)
framesPerDay=24
isoLvls=[500,700,850,925,1000]
numIsoLvls=len(isoLvls)
numFrames=len(grb)
numDays=numFrames//(numChannels*framesPerDay*numIsoLvls)
#INDEX=Frame*5*12+IsoLvl*12+Channel (tot=12*5*24*numDays)
assert numDays==numFrames/(numChannels*framesPerDay*numIsoLvls) #Having integer number of days
assert grb[1].values.shape==gridShape #Check grid shape matches

In [16]:
firstFrame=grb[0]['day']
firstFrame

26

In [14]:

grb[0].values

array([[ 2.18807254e-05,  2.21638475e-05,  2.07631383e-05, ...,
         1.18671451e-05,  1.64567027e-05,  1.98094640e-05],
       [ 2.23277602e-05,  2.30579171e-05,  2.30579171e-05, ...,
        -9.15839337e-06, -4.74764965e-06, -8.58446583e-07],
       [ 1.86471734e-05,  1.93475280e-05,  2.08823476e-05, ...,
        -2.37764325e-05, -2.49834266e-05, -2.48046126e-05],
       ...,
       [ 2.59862281e-06,  2.56882049e-06,  7.06175342e-07, ...,
         8.29086639e-06,  7.35209323e-06,  1.36403833e-05],
       [ 3.32877971e-06,  4.83379699e-06,  3.01585533e-06, ...,
         4.92320396e-06,  5.60865737e-06,  9.14023258e-06],
       [ 5.31063415e-06,  6.38351776e-06,  5.63845970e-06, ...,
         2.21119262e-06,  2.92644836e-06,  5.26593067e-06]])

In [75]:
grbs.message(2)
data, lats, lons = grbs.message(2).data(lat1=0,lat2=100,lon1=100,lon2=320)
reference_time = grb[60].dataDate

# Get the data time offset in hours since reference time
data_time_offset_hours = grb[60].dataTime

# Calculate the actual date and time
data_time = datetime.strptime(str(reference_time), '%Y%m%d')
data_time += timedelta(hours=data_time_offset_hours)

# Convert data time to string
data_time_str = data_time.strftime("%Y-%m-%d %H:%M:%S")
print(data_time_str)

grb[1].latlons()

2022-05-30 04:00:00


(array([[50.  , 50.  , 50.  , ..., 50.  , 50.  , 50.  ],
        [49.75, 49.75, 49.75, ..., 49.75, 49.75, 49.75],
        [49.5 , 49.5 , 49.5 , ..., 49.5 , 49.5 , 49.5 ],
        ...,
        [-4.5 , -4.5 , -4.5 , ..., -4.5 , -4.5 , -4.5 ],
        [-4.75, -4.75, -4.75, ..., -4.75, -4.75, -4.75],
        [-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ]]),
 array([[-180.  , -179.75, -179.5 , ...,  -85.5 ,  -85.25,  275.  ],
        [-180.  , -179.75, -179.5 , ...,  -85.5 ,  -85.25,  275.  ],
        [-180.  , -179.75, -179.5 , ...,  -85.5 ,  -85.25,  275.  ],
        ...,
        [-180.  , -179.75, -179.5 , ...,  -85.5 ,  -85.25,  275.  ],
        [-180.  , -179.75, -179.5 , ...,  -85.5 ,  -85.25,  275.  ],
        [-180.  , -179.75, -179.5 , ...,  -85.5 ,  -85.25,  275.  ]]))

In [71]:
for i in range(0,130):
  reference_time = grb[1].dataDate

  # Get the data time offset in hours since reference time
  data_time_offset_hours = grb[i].dataTime

  # Calculate the actual date and time
  data_time = datetime.strptime(str(reference_time), '%Y%m%d')
  data_time += timedelta(hours=data_time_offset_hours)

  # Convert data time to string
  data_time_str = data_time.strftime("%Y-%m-%d %H:%M:%S")
  print(data_time_str)

2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00
2022-05-26 00:00:00


In [31]:
grb[0:121]

[1:Divergence:s**-1 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 2:Fraction of cloud cover:(0 - 1) (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 3:Geopotential:m**2 s**-2 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 4:Potential vorticity:K m**2 kg**-1 s**-1 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 5:Specific cloud ice water content:kg kg**-1 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 6:Specific cloud liquid water content:kg kg**-1 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 7:Specific humidity:kg kg**-1 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 8:Temperature:K (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:from 202205260000,
 9:U component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 500:fcst time 0 hrs:

In [ ]:
arr=np.zeros(shape=(numDays*framesPerDay,numIsoLvls,numChannels,*gridShape))
print(arr.shape)

def parseIndices(i):
    timeLoc=i//(numChannels*numIsoLvls)
    isoLoc=(i-timeLoc*(numChannels*numIsoLvls))//numChannels
    channelLoc=i-timeLoc*(numChannels*numIsoLvls)-isoLoc*numChannels
    return timeLoc,isoLoc,channelLoc

#INDEX=Frame*60+IsoLvl*12+Channel (tot=12*5*24*numDays)
for i,v in enumerate(grb):
    arr[*parseIndices(i)] = v.values

(144, 5, 12, 221, 381)


In [ ]:

#[0]:24*num_days (3 hours per step) [1]: 5 dimensions  

5

In [ ]:
arr[4,0,7]

array([[253.5320282 , 253.51445007, 253.50175476, ..., 258.3523407 ,
        258.3445282 , 258.33769226],
       [253.50273132, 253.4851532 , 253.4773407 , ..., 258.87773132,
        258.83866882, 258.8054657 ],
       [253.47148132, 253.4539032 , 253.44511414, ..., 259.42167664,
        259.3679657 , 259.30937195],
       ...,
       [269.5242157 , 269.4851532 , 269.50663757, ..., 266.6414032 ,
        266.57987976, 266.50761414],
       [269.42070007, 269.44706726, 269.5242157 , ..., 266.60527039,
        266.53495789, 266.46269226],
       [269.34941101, 269.43632507, 269.53593445, ..., 266.55741882,
        266.48124695, 266.42070007]])

In [ ]:
inTensor=arr.reshape(numDays*framesPerDay,*gridShape,numChannels*numIsoLvls)
print(inTensor.shape)
inTensor

(144, 221, 381, 60)


array([[[[ 2.18807254e-05,  2.21638475e-05,  2.07631383e-05, ...,
          -2.45287083e-06, -3.04891728e-06, -3.82377766e-06],
         [-4.59863804e-06, -5.53741120e-06, -6.61029480e-06, ...,
           1.15244184e-05,  1.33870635e-05,  1.51752029e-05],
         [ 1.82299409e-05,  1.93177257e-05,  1.41768251e-05, ...,
           3.74601223e-06,  3.52249481e-06,  2.59862281e-06],
         ...,
         [-3.94298695e-06,  9.59495082e-07,  3.98443080e-06, ...,
          -2.87832227e-05, -2.27184501e-05, -1.51039567e-05],
         [-1.27644744e-05, -2.12134328e-05, -1.35393348e-05, ...,
          -1.10508408e-05, -3.40284314e-05, -3.70235648e-05],
         [-2.77848449e-05, -1.91868749e-05, -1.11402478e-05, ...,
          -4.45784535e-05, -1.24217477e-05,  3.57090030e-05]],

        [[ 1.37893949e-05,  3.47702298e-05,  5.08336816e-05, ...,
          -2.02795491e-07,  2.12178566e-06,  4.89340164e-06],
         [ 8.26106407e-06,  1.06899533e-05,  1.22843776e-05, ...,
          -1.75626483e

In [ ]:
inTensor.size*inTensor.itemsize

5819973120

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, TimeDistributed, LSTM

# Define your model
model = Sequential()

# Assuming you flatten the equipotential surface and attribute dimensions into the channel dimension
# Inpmay need to adjust the input shape based on how you preprocess your data

# TimeDistributed Wrapper allows the same CNN to be applied to each time step independently
model.add(TimeDistributed(Conv2D(filters=32, kernel_size=(3, 3), activation='relu'), input_shape=(None, *gridShape, 60)))
model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))

model.add(TimeDistributed(Conv2D(filters=64, kernel_size=(3, 3), activation='relu')))
model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))

#中融合/autoencoder?

model.add(TimeDistributed(Flatten()))

# Add LSTM layer to capture temporal dependencies - consider this for later stages
# model.add(LSTM(units=50))

model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2))  # Predicting 2 values for the cyclone's next location; adjust based on your output

model.compile(optimizer='adam', loss='mean_squared_error')  # Use mean squared error for regression problems

model.summary()

# Training the model will require your data to be in the shape expected by the input layer
# X_train: Your feature data, y_train: Your target data (cyclone's next location or movement category)
# model.fit(X_train, y_train, epochs=10, batch_size=32)ut shape: (Time, Height, Width, Channels) where Channels = 5 equipotential surfaces * 12 attributes
# You 

2024-03-28 09:56:47.605607: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/lixueting/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/wrapper.py:27: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ time_distributed                │ (None, None, 219, 379, │        17,312 │
│ (TimeDistributed)               │ 32)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_1              │ (None, None, 109, 189, │             0 │
│ (TimeDistributed)               │ 32)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_2              │ (None, None, 107, 187, │        18,496 │
│ (TimeDistributed)               │ 64)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_3              │ (None, None, 53, 93,   │             0 │
│ (TimeDistributed)               │ 64)                    │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_4              │ (None, None, 315456)   │             0 │
│ (TimeDistributed)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, None, 100)      │    31,545,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, None, 2)        │           202 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,581,710 (120.47 MB)

 Trainable params: 31,581,710 (120.47 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:

# num_channels = 60
# gridShape=(221,381)
numChannels = 12
framesPerDay=24
isoLvls=[500,700,850,925,1000]
numIsoLvls=len(isoLvls)
# numFrames=len(grb)
# numDays=numFrames//(numChannels*framesPerDay*numIsoLvls)
# #INDEX=Frame*5*12+IsoLvl*12+Channel (tot=12*5*24*numDays)

# x values
# open file
grib = input("filename:")
if grib[6] != '(':
  grib_file = pygrib.open(grib)
else:
  second = grib[:7] + '2' +grib[8:]
  
  # Open the first GRIB2 file
  grbs1 = pygrib.open(grib)
  # Open the second GRIB2 file
  grbs2 = pygrib.open(second)

  # Iterate over messages in the first file
  data1 = []
  for grb in grbs1:
      # Process each message and extract data as needed
      data1.append(grb.values)

  # Iterate over messages in the second file
  data2 = []
  for grb in grbs2:
      # Process each message and extract data as needed
      data2.append(grb.values)

  # Combine data from both files
  grib_file = data1 + data2


grb_df=grib_file[1:]
grb_df.append(grib_file[len(grb)+1])



def parseIndices(i):
    timeLoc=i//(numChannels*numIsoLvls)
    isoLoc=(i-timeLoc*(numChannels*numIsoLvls))//numChannels
    channelLoc=i-timeLoc*(numChannels*numIsoLvls)-isoLoc*numChannels
    return timeLoc,isoLoc,channelLoc

#INDEX=Frame*60+IsoLvl*12+Channel (tot=12*5*24*numDays)
for i,v in enumerate(grb_df):
    arr[*parseIndices(i)] = v.values

size = arr.shape
print(size)

image_height = size[3]
image_width = size[4]

gridShape = (image_height, image_width)

numFrames=len(grib_file)
numDays=numFrames//(numChannels*framesPerDay*numIsoLvls)
#INDEX=Frame*5*12+IsoLvl*12+Channel (tot=12*5*24*numDays)

arr=np.zeros(shape=(numDays*framesPerDay,numIsoLvls,numChannels,*gridShape))

inTensor=arr.reshape(numDays*framesPerDay,*gridShape,numChannels*numIsoLvls)
print(inTensor.shape)
inTensor

#y values
df = pd.read_csv('BestTrack_Trimmed.csv')
y_df = df[df['SEASON']==grib[:4]]
reorder = y_df.groupby['NAME']

groups = [group for _, group in reorder]
group_names = [name for name, _ in reorder]

# Change the following according to each year's sequence
# Exchange the second and third groups
groups[2], groups[3] = groups[3], groups[2]
group_names[2], group_names[3] = group_names[3], group_names[2]
groups.insert(-1, groups.pop(11))
group_names.insert(-1, group_names.pop(11))

# for name, group in zip(group_names, groups):
#     print("Group:", name)
#     # print(group)

group_names = list(reorder.groups.keys())
groups = list(reorder.groups.values())
concatenated_df = pd.concat([y_df.loc[group] for group in groups])


for i in range(0,len(concatenated_df))
y_time_string = concatenated_df.iloc[0]['ISO_TIME']



# x_train = tf.random.normal((num_samples, image_height, image_width, num_channels))
# y_train = tf.random.uniform((num_samples,), minval=0, maxval=2, dtype=tf.int32)

In [17]:
df = pd.read_csv('BestTrack_Trimmed.csv')
test_df = df[df['SEASON']==2022]

In [72]:
# len(test_df[test_df['NAME']=='AGATHA'])
order = test_df.groupby('NAME')
print(order)
# buffer = order.iloc[2]
# order.iloc[2] = order.iloc[3]
# order.iloc[3] = buffer
# for name, group in order:
#     print("Group:", name)

groups = [group for _, group in order]
group_names = [name for name, _ in order]

# Exchange the second and third groups
groups[2], groups[3] = groups[3], groups[2]
group_names[2], group_names[3] = group_names[3], group_names[2]
groups.insert(-1, groups.pop(11))
group_names.insert(-1, group_names.pop(11))

for name, group in zip(group_names, groups):
    print("Group:", name)
    # print(group)

# group_names = list(order.groups.keys())
# groups = list(order.groups.values())
# concatenated_df = pd.concat([test_df.loc[group] for group in groups])
# print(concatenated_df.iloc[2]['ISO_TIME'])


Group: AGATHA
Group: BLAS
Group: CELIA
Group: BONNIE
Group: DARBY
Group: ESTELLE
Group: FRANK
Group: GEORGETTE
Group: HOWARD
Group: IVETTE
Group: JAVIER
Group: KAY
Group: LESTER
Group: MADELINE
Group: NEWTON
Group: ORLENE
Group: PAINE
Group: JULIA
Group: ROSLYN


In [41]:
len(test_df[test_df['NAME']=='BLAS'])

69